#!/bin/sh                                                                                       

SID="org.webosinternals.secureshell"

APPS=/media/cryptofs/apps

[ -d $APPS ] || { echo "Requires webOS 1.3.5 or later" ; exit 1 ; }

# Remove the daemon executable
rm -f /var/usr/sbin/${SID}

# Stop the daemon if running
/sbin/stop ${SID} || true
/usr/bin/killall -9 ${SID} || true

# Remove the upstart script
rm -f /var/palm/event.d/${SID}

# Install the daemon executable
mkdir -p /var/usr/sbin/
install -m 755 $APPS/usr/palm/applications/${SID}/bin/${SID} /var/usr/sbin/${SID}

# Install the upstart script
mkdir -p /var/palm/event.d
cp $APPS/usr/palm/applications/${SID}/upstart/${SID} /var/palm/event.d/${SID}

# Start the daemon
/sbin/start ${SID}

exit 0
